/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  varchar,
  integer,
  timestamp,
  jsonb,
  numeric,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'manager'])

export const audit_logs = pgTable(
  'audit_logs',
  {
    id: serial('id').primaryKey(),
    action: varchar('action'),
    collection: varchar('collection'),
    docID: varchar('doc_i_d'),
    deletedBy: integer('deleted_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    timestamp: timestamp('timestamp', { mode: 'string', withTimezone: true, precision: 3 }),
    data: jsonb('data'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('audit_logs_deleted_by_idx').on(columns.deletedBy),
    index('audit_logs_updated_at_idx').on(columns.updatedAt),
    index('audit_logs_created_at_idx').on(columns.createdAt),
  ],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    role: enum_users_role('role').notNull().default('manager'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    description: varchar('description'),
    prefix: varchar('prefix').default('uploads/media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
    sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
    sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
    sizes_medium_url: varchar('sizes_medium_url'),
    sizes_medium_width: numeric('sizes_medium_width', { mode: 'number' }),
    sizes_medium_height: numeric('sizes_medium_height', { mode: 'number' }),
    sizes_medium_mimeType: varchar('sizes_medium_mime_type'),
    sizes_medium_filesize: numeric('sizes_medium_filesize', { mode: 'number' }),
    sizes_medium_filename: varchar('sizes_medium_filename'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
      columns.sizes_thumbnail_filename,
    ),
    index('media_sizes_medium_sizes_medium_filename_idx').on(columns.sizes_medium_filename),
  ],
)

export const trails_3d_objects = pgTable(
  'trails_3d_objects',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    caption: varchar('caption'),
  },
  (columns) => [
    index('trails_3d_objects_order_idx').on(columns._order),
    index('trails_3d_objects_parent_id_idx').on(columns._parentID),
    index('trails_3d_objects_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [trails.id],
      name: 'trails_3d_objects_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const trails = pgTable(
  'trails',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    subTitle: varchar('sub_title'),
    description: varchar('description').notNull(),
    location: varchar('location'),
    completion: varchar('completion'),
    architect: varchar('architect'),
    yearsOfUse: varchar('years_of_use'),
    nameToday: varchar('name_today'),
    otherHistoricalNames: varchar('other_historical_names'),
    trailImage: integer('trail_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    coordinatesGroup_x: numeric('coordinates_group_x', { mode: 'number' }).notNull().default(0),
    coordinatesGroup_y: numeric('coordinates_group_y', { mode: 'number' }).notNull().default(0),
    content: jsonb('content'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('trails_trail_image_idx').on(columns.trailImage),
    index('trails_background_image_idx').on(columns.backgroundImage),
    index('trails_updated_at_idx').on(columns.updatedAt),
    index('trails_created_at_idx').on(columns.createdAt),
  ],
)

export const _trails_v_version_3d_objects = pgTable(
  '_trails_v_version_3d_objects',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    caption: varchar('caption'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_trails_v_version_3d_objects_order_idx').on(columns._order),
    index('_trails_v_version_3d_objects_parent_id_idx').on(columns._parentID),
    index('_trails_v_version_3d_objects_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_trails_v.id],
      name: '_trails_v_version_3d_objects_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _trails_v = pgTable(
  '_trails_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => trails.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title').notNull(),
    version_subTitle: varchar('version_sub_title'),
    version_description: varchar('version_description').notNull(),
    version_location: varchar('version_location'),
    version_completion: varchar('version_completion'),
    version_architect: varchar('version_architect'),
    version_yearsOfUse: varchar('version_years_of_use'),
    version_nameToday: varchar('version_name_today'),
    version_otherHistoricalNames: varchar('version_other_historical_names'),
    version_trailImage: integer('version_trail_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_backgroundImage: integer('version_background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_coordinatesGroup_x: numeric('version_coordinates_group_x', { mode: 'number' })
      .notNull()
      .default(0),
    version_coordinatesGroup_y: numeric('version_coordinates_group_y', { mode: 'number' })
      .notNull()
      .default(0),
    version_content: jsonb('version_content'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('_trails_v_parent_idx').on(columns.parent),
    index('_trails_v_version_version_trail_image_idx').on(columns.version_trailImage),
    index('_trails_v_version_version_background_image_idx').on(columns.version_backgroundImage),
    index('_trails_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_trails_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_trails_v_created_at_idx').on(columns.createdAt),
    index('_trails_v_updated_at_idx').on(columns.updatedAt),
  ],
)

export const guided_tours_images = pgTable(
  'guided_tours_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    caption: varchar('caption'),
  },
  (columns) => [
    index('guided_tours_images_order_idx').on(columns._order),
    index('guided_tours_images_parent_id_idx').on(columns._parentID),
    index('guided_tours_images_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [guided_tours.id],
      name: 'guided_tours_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const guided_tours = pgTable(
  'guided_tours',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    subTitle: varchar('sub_title'),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    time: timestamp('time', { mode: 'string', withTimezone: true, precision: 3 }),
    venue: varchar('venue'),
    admission: varchar('admission'),
    content: jsonb('content'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('guided_tours_updated_at_idx').on(columns.updatedAt),
    index('guided_tours_created_at_idx').on(columns.createdAt),
  ],
)

export const _guided_tours_v_version_images = pgTable(
  '_guided_tours_v_version_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    caption: varchar('caption'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_guided_tours_v_version_images_order_idx').on(columns._order),
    index('_guided_tours_v_version_images_parent_id_idx').on(columns._parentID),
    index('_guided_tours_v_version_images_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_guided_tours_v.id],
      name: '_guided_tours_v_version_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _guided_tours_v = pgTable(
  '_guided_tours_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => guided_tours.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title').notNull(),
    version_subTitle: varchar('version_sub_title'),
    version_startDate: timestamp('version_start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_endDate: timestamp('version_end_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_time: timestamp('version_time', { mode: 'string', withTimezone: true, precision: 3 }),
    version_venue: varchar('version_venue'),
    version_admission: varchar('version_admission'),
    version_content: jsonb('version_content'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('_guided_tours_v_parent_idx').on(columns.parent),
    index('_guided_tours_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_guided_tours_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_guided_tours_v_created_at_idx').on(columns.createdAt),
    index('_guided_tours_v_updated_at_idx').on(columns.updatedAt),
  ],
)

export const roving_exhibitions_images = pgTable(
  'roving_exhibitions_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    caption: varchar('caption'),
  },
  (columns) => [
    index('roving_exhibitions_images_order_idx').on(columns._order),
    index('roving_exhibitions_images_parent_id_idx').on(columns._parentID),
    index('roving_exhibitions_images_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [roving_exhibitions.id],
      name: 'roving_exhibitions_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const roving_exhibitions = pgTable(
  'roving_exhibitions',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    subTitle: varchar('sub_title'),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    time: timestamp('time', { mode: 'string', withTimezone: true, precision: 3 }),
    venue: varchar('venue'),
    admission: varchar('admission'),
    content: jsonb('content'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('roving_exhibitions_updated_at_idx').on(columns.updatedAt),
    index('roving_exhibitions_created_at_idx').on(columns.createdAt),
  ],
)

export const _roving_exhibitions_v_version_images = pgTable(
  '_roving_exhibitions_v_version_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    file: integer('file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    caption: varchar('caption'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_roving_exhibitions_v_version_images_order_idx').on(columns._order),
    index('_roving_exhibitions_v_version_images_parent_id_idx').on(columns._parentID),
    index('_roving_exhibitions_v_version_images_file_idx').on(columns.file),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_roving_exhibitions_v.id],
      name: '_roving_exhibitions_v_version_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _roving_exhibitions_v = pgTable(
  '_roving_exhibitions_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => roving_exhibitions.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title').notNull(),
    version_subTitle: varchar('version_sub_title'),
    version_startDate: timestamp('version_start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_endDate: timestamp('version_end_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_time: timestamp('version_time', { mode: 'string', withTimezone: true, precision: 3 }),
    version_venue: varchar('version_venue'),
    version_admission: varchar('version_admission'),
    version_content: jsonb('version_content'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('_roving_exhibitions_v_parent_idx').on(columns.parent),
    index('_roving_exhibitions_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_roving_exhibitions_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_roving_exhibitions_v_created_at_idx').on(columns.createdAt),
    index('_roving_exhibitions_v_updated_at_idx').on(columns.updatedAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'audit-logsID': integer('audit_logs_id'),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    trailsID: integer('trails_id'),
    'guided-toursID': integer('guided_tours_id'),
    'roving-exhibitionsID': integer('roving_exhibitions_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_audit_logs_id_idx').on(columns['audit-logsID']),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_trails_id_idx').on(columns.trailsID),
    index('payload_locked_documents_rels_guided_tours_id_idx').on(columns['guided-toursID']),
    index('payload_locked_documents_rels_roving_exhibitions_id_idx').on(
      columns['roving-exhibitionsID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['audit-logsID']],
      foreignColumns: [audit_logs.id],
      name: 'payload_locked_documents_rels_audit_logs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['trailsID']],
      foreignColumns: [trails.id],
      name: 'payload_locked_documents_rels_trails_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['guided-toursID']],
      foreignColumns: [guided_tours.id],
      name: 'payload_locked_documents_rels_guided_tours_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['roving-exhibitionsID']],
      foreignColumns: [roving_exhibitions.id],
      name: 'payload_locked_documents_rels_roving_exhibitions_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_audit_logs = relations(audit_logs, ({ one }) => ({
  deletedBy: one(users, {
    fields: [audit_logs.deletedBy],
    references: [users.id],
    relationName: 'deletedBy',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_trails_3d_objects = relations(trails_3d_objects, ({ one }) => ({
  _parentID: one(trails, {
    fields: [trails_3d_objects._parentID],
    references: [trails.id],
    relationName: '3dObjects',
  }),
  file: one(media, {
    fields: [trails_3d_objects.file],
    references: [media.id],
    relationName: 'file',
  }),
}))
export const relations_trails = relations(trails, ({ one, many }) => ({
  trailImage: one(media, {
    fields: [trails.trailImage],
    references: [media.id],
    relationName: 'trailImage',
  }),
  backgroundImage: one(media, {
    fields: [trails.backgroundImage],
    references: [media.id],
    relationName: 'backgroundImage',
  }),
  '3dObjects': many(trails_3d_objects, {
    relationName: '3dObjects',
  }),
}))
export const relations__trails_v_version_3d_objects = relations(
  _trails_v_version_3d_objects,
  ({ one }) => ({
    _parentID: one(_trails_v, {
      fields: [_trails_v_version_3d_objects._parentID],
      references: [_trails_v.id],
      relationName: 'version_3dObjects',
    }),
    file: one(media, {
      fields: [_trails_v_version_3d_objects.file],
      references: [media.id],
      relationName: 'file',
    }),
  }),
)
export const relations__trails_v = relations(_trails_v, ({ one, many }) => ({
  parent: one(trails, {
    fields: [_trails_v.parent],
    references: [trails.id],
    relationName: 'parent',
  }),
  version_trailImage: one(media, {
    fields: [_trails_v.version_trailImage],
    references: [media.id],
    relationName: 'version_trailImage',
  }),
  version_backgroundImage: one(media, {
    fields: [_trails_v.version_backgroundImage],
    references: [media.id],
    relationName: 'version_backgroundImage',
  }),
  version_3dObjects: many(_trails_v_version_3d_objects, {
    relationName: 'version_3dObjects',
  }),
}))
export const relations_guided_tours_images = relations(guided_tours_images, ({ one }) => ({
  _parentID: one(guided_tours, {
    fields: [guided_tours_images._parentID],
    references: [guided_tours.id],
    relationName: 'images',
  }),
  file: one(media, {
    fields: [guided_tours_images.file],
    references: [media.id],
    relationName: 'file',
  }),
}))
export const relations_guided_tours = relations(guided_tours, ({ many }) => ({
  images: many(guided_tours_images, {
    relationName: 'images',
  }),
}))
export const relations__guided_tours_v_version_images = relations(
  _guided_tours_v_version_images,
  ({ one }) => ({
    _parentID: one(_guided_tours_v, {
      fields: [_guided_tours_v_version_images._parentID],
      references: [_guided_tours_v.id],
      relationName: 'version_images',
    }),
    file: one(media, {
      fields: [_guided_tours_v_version_images.file],
      references: [media.id],
      relationName: 'file',
    }),
  }),
)
export const relations__guided_tours_v = relations(_guided_tours_v, ({ one, many }) => ({
  parent: one(guided_tours, {
    fields: [_guided_tours_v.parent],
    references: [guided_tours.id],
    relationName: 'parent',
  }),
  version_images: many(_guided_tours_v_version_images, {
    relationName: 'version_images',
  }),
}))
export const relations_roving_exhibitions_images = relations(
  roving_exhibitions_images,
  ({ one }) => ({
    _parentID: one(roving_exhibitions, {
      fields: [roving_exhibitions_images._parentID],
      references: [roving_exhibitions.id],
      relationName: 'images',
    }),
    file: one(media, {
      fields: [roving_exhibitions_images.file],
      references: [media.id],
      relationName: 'file',
    }),
  }),
)
export const relations_roving_exhibitions = relations(roving_exhibitions, ({ many }) => ({
  images: many(roving_exhibitions_images, {
    relationName: 'images',
  }),
}))
export const relations__roving_exhibitions_v_version_images = relations(
  _roving_exhibitions_v_version_images,
  ({ one }) => ({
    _parentID: one(_roving_exhibitions_v, {
      fields: [_roving_exhibitions_v_version_images._parentID],
      references: [_roving_exhibitions_v.id],
      relationName: 'version_images',
    }),
    file: one(media, {
      fields: [_roving_exhibitions_v_version_images.file],
      references: [media.id],
      relationName: 'file',
    }),
  }),
)
export const relations__roving_exhibitions_v = relations(
  _roving_exhibitions_v,
  ({ one, many }) => ({
    parent: one(roving_exhibitions, {
      fields: [_roving_exhibitions_v.parent],
      references: [roving_exhibitions.id],
      relationName: 'parent',
    }),
    version_images: many(_roving_exhibitions_v_version_images, {
      relationName: 'version_images',
    }),
  }),
)
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    'audit-logsID': one(audit_logs, {
      fields: [payload_locked_documents_rels['audit-logsID']],
      references: [audit_logs.id],
      relationName: 'audit-logs',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    trailsID: one(trails, {
      fields: [payload_locked_documents_rels.trailsID],
      references: [trails.id],
      relationName: 'trails',
    }),
    'guided-toursID': one(guided_tours, {
      fields: [payload_locked_documents_rels['guided-toursID']],
      references: [guided_tours.id],
      relationName: 'guided-tours',
    }),
    'roving-exhibitionsID': one(roving_exhibitions, {
      fields: [payload_locked_documents_rels['roving-exhibitionsID']],
      references: [roving_exhibitions.id],
      relationName: 'roving-exhibitions',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  audit_logs: typeof audit_logs
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  trails_3d_objects: typeof trails_3d_objects
  trails: typeof trails
  _trails_v_version_3d_objects: typeof _trails_v_version_3d_objects
  _trails_v: typeof _trails_v
  guided_tours_images: typeof guided_tours_images
  guided_tours: typeof guided_tours
  _guided_tours_v_version_images: typeof _guided_tours_v_version_images
  _guided_tours_v: typeof _guided_tours_v
  roving_exhibitions_images: typeof roving_exhibitions_images
  roving_exhibitions: typeof roving_exhibitions
  _roving_exhibitions_v_version_images: typeof _roving_exhibitions_v_version_images
  _roving_exhibitions_v: typeof _roving_exhibitions_v
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_audit_logs: typeof relations_audit_logs
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_trails_3d_objects: typeof relations_trails_3d_objects
  relations_trails: typeof relations_trails
  relations__trails_v_version_3d_objects: typeof relations__trails_v_version_3d_objects
  relations__trails_v: typeof relations__trails_v
  relations_guided_tours_images: typeof relations_guided_tours_images
  relations_guided_tours: typeof relations_guided_tours
  relations__guided_tours_v_version_images: typeof relations__guided_tours_v_version_images
  relations__guided_tours_v: typeof relations__guided_tours_v
  relations_roving_exhibitions_images: typeof relations_roving_exhibitions_images
  relations_roving_exhibitions: typeof relations_roving_exhibitions
  relations__roving_exhibitions_v_version_images: typeof relations__roving_exhibitions_v_version_images
  relations__roving_exhibitions_v: typeof relations__roving_exhibitions_v
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
